### ISSUE TITLE
Issue using cut when read in "empty" mpt data

### ISSUE THREAD

**Issue by KimDegnJensen** [ixdat/ixdat#93] opened 2022-07-20 11:55 UTC
**Fun little error, ixdat build-in functions are perfectly fine filling in an empty  .mpt experiment (txt file w. preamble but no actual data). The package will allow someting like this without any error**
data_dir_MS =  Path(r"experiment.tsv")
data_dir_EC_1 =  Path(r"experiment_mpt_file_1.mpt")
data_dir_EC_1 =  Path(r"experiment_mpt_file_1.mpt")
data_dir_EC_2 =  Path(r"experiment_mpt_file_2.mpt") #this is a "empty" mpt file which have been exported by error
data_dir_EC_3 =  Path(r"experiment_mpt_file_3.mpt") 
data_MS = ixdat.Measurement.read(data_dir_MS, technique="MS", reader="zilien")
data_EC_1 = ixdat.Measurement.read(data_dir_EC_1, reader="biologic")
data_EC_2 = ixdat.Measurement.read(data_dir_EC_2, reader="biologic")
data_EC_3 = ixdat.Measurement.read(data_dir_EC_3, reader="biologic")

full_ECMS_data=data_MS+data_EC_1+data_EC_2+data_EC_3

axes = full_ECMS_data.plot_measurement()
full_plot = axes[0].get_figure() 

**Data "looks" fine and is plottable, but using cut tool as such**
relevant_ECMS_data = ful_ECMS_data.cut(tspan=[tmin,tmax]) 

 **this promts an error looking like this**

  File "C:\...\anaconda3\lib\site-packages\ixdat\measurements.py", line 978, in tspan
    t_start = min(t_start, t[0]) if t_start else t[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

**Other functions like grab etc. still work, so 1) maybe its only the cut function which have problem with the establishing a meaningfull t array 2) its hard for me to figure out whihc functions are affected 3) maybe the easiest way to solve this is stopping empty experiments to be readable e.g. by prompting a warning sayin "file X1 and X2" was empty so have been ignored**

**Comment by ScottSoren** [comment] 2022-07-21 07:03
Nice bug catch!
I would prefer to keep empty files readable, since this spares the user the headache of going through and deleting empty files when using a loop or `read_set` which reads a bunch. 

I think this bug has to do with the fact that `Measurement.cut` also cuts all the `component_measurements` (this necessary for the `file_number` selector to get built correctly in the cut measurement), resulting in it trying to cut the empty measurement. I think the easiest fix is to get it to leave out empty measurements from `component_measurements`. 

I don't have a set of files at hand to test it on though.... can you share with me the file set you used in the example? Thanks!

If you get me files to test a bug fix, I think this will be a quick fix, and can probably make #92 and ixdat 0.2.4, to be released very soon. :)

**Comment by KimDegnJensen** [comment] 2022-07-21 07:51
Hi Søren
Ive send you 3 files from the same experiment which you can export to mpt
and then run in your program, i though it would be nice also to have some
data from the experiment that actually works with ixdat as is. (so 1 large
data file with working data and 2 ca 15kb files only containing experiment
meta data, no actual data when exporting to mpt).
I think I will make my "own solution" as the problem arose due to the way i
read  data in ixdat (automatically using a for loop). i think a simple
header length vs. data length should be sufficient not to read in
incomplete/bad experiment and just prompt a warning saying "data_x...data_y
etc has not been read as these appear to be incomplete experiments."
Nb i finished another script for making statistics of CVs, ill forward it
soon.
Next i think ill try to make different background subtraction functions
(e.g. linear and exponentials, even errc backgrounds could likely be
useful) and in that context ill do some CO stripping functions as I think
these would be super useful. They'll mostly be based on what you already
did, but with some slightly different/to-some extend automated dependents)

Lastly, concerning this issue my solution was also just to "delete" mpt
files with empty data, i believe some universal fix would  be needed e.g.
i've been trying to work with different packages

from galvani import BioLogic
or
import eclabfiles as ecf
to see if i can automate the exporting to mpt process so all data
treatment goes though python and by extension ixdat. It is not super
important but for now i can get the galvana package to export data (except
the meta data) conversely using the eclabfiles prompt and formatting error
but should in principle be able to deliver data+meta data for each mpr file.
Either way, thanks for your reply and let me know how it goes
KR Kim

**Comment by ScottSoren** [comment] 2022-07-21 09:06
Hey Kim,
Where did you send the test files? I don't see them in Slack or my email (sbscott@ic.ac.uk)

**Comment by ScottSoren** [comment] 2022-07-21 09:26
I think I've resolved it here: https://github.com/ixdat/ixdat/pull/92/commits/7e35847d633de69063899bfd8d99402729b7755a

**Comment by ScottSoren** [comment] 2022-07-25 12:45
@KimDegnJensen , 
I think I've solved this now in ixdat 0.2.4m, so I'm closing this Issue. Please reopen this if not.

**Comment by AnnaWiniwarter** [comment] 2023-10-10 10:05
Reopening this issue since I ran into a very similar problem involving mpt files that don't contain any data (i.e. just the header): 
I was trying to use the automatic tspan selection in `ECMSMeasurement.ecms_calibration_curve()` using "selector" as selector and passing a number of cycles. 
I load the mpt files using `Measurement.read_set()` which sometimes includes empty mpt files (i.e. those that don't contain any data). If I do this, I get an error about t_start being 0.
The error seems to start in `ECMSMeasurement.select_value()`, so I tried that separately and I get this error (so I suppose `cut()` IS still the issue):
![image](https://github.com/ixdat/ixdat/assets/96479350/7734e3d8-ef05-4085-881b-07e67c2d4d14)

If I remove the empty mpt files, everything runs smoothly.

**Comment by ScottSoren** [comment] 2023-10-31 16:27
@AnnaWiniwarter , 
I've found a dataset that reproduces the problem and solved the issue in PR #131, which now awaits your review :) 
The dataset I used: https://www.dropbox.com/scl/fo/z1599uzzi0avmtco67bsd/h?rlkey=ozhkgtq5cfp467j8kavpnoe3c&dl=0

**Comment by ScottSoren** [comment] 2023-10-31 18:02
solved.

**Closed by ScottSoren** 2023-10-31 18:02 UTC
Labels: bug
