### ISSUE TITLE
Did not find any "time/s" column in MPT file, even though it is there

### ISSUE THREAD

**Issue by matenestor** [ixdat/ixdat#108] opened 2023-02-24 16:09 UTC
Ixdat can't parse MPT files that were generated post-measurement from MPR files. Such files have just a few metadata lines:

```tsv
EC-Lab ASCII FILE                                                               
Nb header lines : 3                                                             
freq/Hz Re(Z)/Ohm   -Im(Z)/Ohm  |Z|/Ohm Phase(Z)/deg    time/s  <Ewe>/V <I>/mA ...
1,9999814E+005  6,6673303E+002  -2,7343878E+002  7,2062592E+002  2,2299385E+001   3,244848644788726E+001  2,4071446E-001  -1,4733075E-002 ...
...
```

The problem is `biologic.py:process_header_line()` method. The `self.N_header_lines` attribute is filled correctly, but the code never gets to the point where it changes the state of the `self.place_in_file` attribute to  `"column names"`, because it never finds a value for the `self.timestamp_string`.

I was able to read my files when I changed it myself in the first `if` condition where `self.N_header_lines` is filled. **Together with `self.tstamp`**, because that is necessary, when you want to plot the measurement. The value from that I took from the timestamp in the filename.

**Comment by ScottSoren** [comment] 2023-02-25 11:48
Oh no. I saw this once, ages ago (pre-ixdat). It was strangely specific to a certain experiment or certain installation of EC-Lab, I don't remember. Can you add that information here? Normally, post-conversion of .mpr to .mpt works fine, generating the full header.
Modifying the reader so that it can handle these stump-header .mpt files is easy, as you describe, but the problem is, how can one then know the timestamp? Without this knowledge from somewhere, it is impossible to synchronize with other techniques. 
If, as described in #107 , the EC-Lab data is generated in connection with Zilien, is there an offset value stored in the .tsv file that could be used?

**Comment by tugce-y** [comment] 2023-02-27 12:16
I was never able to plot the post-converted .mpt files with ixdat, I always get this error regardless of the technique (chronoamperometry, chronopotentiometry, CV) if that's what you're asking.

I do the conversion from .mpr file to .mpt file from EC-lab>Experiment>Export as text file, which results in 3 lines header without any timestamp info. I don't know if there is a specific way of converting .mpr to .mpt to avoid this.

**Comment by matenestor** [comment] 2023-03-14 08:52
There are timestamps in the .tsv file, but the values don't really match. I will discuss that here in Spectro if the timestamps can be used somehow.

**Comment by ScottSoren** [comment] 2023-03-14 16:14
@tugce-y , annoying that this problem is there for all techniques! but I have definitely converted many .mpr files to .mpt without truncated header before, so there is something specific going on. Can you share for the record here, what version of EC-Lab was used, both to generate the .mpr files and for the conversion to .mpt?

**Comment by ScottSoren** [comment] 2023-09-15 11:14
@tugce-y , did you ever figure out what was causing the truncated file headers in the .mpt‘s?
If not I'll close this issue as a Biologic problem.
https://www.biologic.net/contact/?form=support

**Comment by tugce-y** [comment] 2023-09-15 12:16
@ScottSoren, I don't know the reason but if I enable text export option in EC-Lab > Safety/Adv. Settings > Data Process **before the experiment** there is no problem with time stamps. 
For the post conversion, @matenestor manually aligned the EC time and MS time approximately, which is not ideal. This issue happened to me both in DTU and Spectro Inlets. I know the EC-lab version in DTU is 11.36. I don't remember what was the version in Spectro.

**Comment by ScottSoren** [comment] 2023-09-15 13:25
Thanks for the update, @tugce-y !
I'll add a note in the documentation of the biologic module that text export syoud be enabled.

**Closed by ScottSoren** 2023-09-15 13:25 UTC
Labels: Needs info, biologic

**Comment by ScottSoren** [comment] 2023-11-08 08:40
@tugce-y and @matenestor , this may interest you: https://github.com/ixdat/ixdat/pull/134
It will soon be possible to just read the .mpr files when something like this is wrong with the .mpt files :) . Feel free to comment on that PR.
