### ISSUE TITLE
Plot EC data only when importing a file from zilien

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#32] opened 2022-02-02 10:12 UTC
I would like to plot only the EC data from data imported from a Zilien file. 
If I want to only plot MS data there is the workaround to use MSMeasurement.import("filepath/data.tsv", reader = zilien). This imports only the ms data from zilien, which means that plot_experiment() then only plots the ms data. 
I tried to used ixdat.techniques.ec.ECMeasurement.import("filepath/data.tsv", reader = zilien), but this still creates an ECMSMeasurement object. I can of course just directly import the biologic files, and will do that, but it would be nice I could just use the zilien file.

In general, it would be great to have plotting features to plot only the MS or only the EC data (both vs time and vs potential).

**Comment by ScottSoren** [comment] 2022-02-02 10:54
HI Anna,
Thanks for the issues! I guess a really satisfying solution to this is to be able to split up the data from a hyphenated measurement, and is thus related to #31. That will wait until after #30 , but the "pluggability" of ixdat lends itself to workarounds :)
For this one, a workaround is to switch out the plotter for an ECPlotter. The following code works:
```
from ixdat import Measurement
from ixdat.plotters import ECPlotter

# This imports it with the EC data, and plots EC and MS together.
ecms = Measurement.read("path/to/my/tsv/file", reader="zilien")
ecms.plot_measurement()

# This plots just the EC data
ECPlotter(measurement=ecms).plot_measurement()

```
Hope that helps!

On a side note, the reason that switching out the class from which you call `read()` doesn't work like it did for getting an `MSMeasurement` (#31) is that by convention so far ixdat readers will respect the reader's default measurement type rather than the class you call `read()` from **if** the reader's default type is more specific than the class you call `read()` from. Here "more specific than" means "inherits from". This is what enables you to use the base class `Measurement` to read anything. But `ECMSMeasurement` inherits from both `ECMeasurement` and `MSMeasurement` and so would override them too, even though clearly the user sometimes doesn't want that. It only works for `MSMeasurement` because I hard-coded it in the reader (this code: https://github.com/ixdat/ixdat/blob/ef61fa40ede67e0b5b3ca83c6931e3335214f575/src/ixdat/readers/zilien.py#L27 ). 
But maybe this is stupid? Maybe the reader should respect the class from which `read()` was called and **only** use the reader's default class when the user called plain `Measurement.read()` . 

@KennethNielsen , What do you think? 


On another side note, this doesn't work right now (maybe it should?): It tells you you can't set the plotter.
```
# ecms.plotter = ECPlotter()  # raises AttributeError
# ecms.plot()
````

**Comment by AnnaWiniwarter** [comment] 2022-02-02 13:25
Hi Soren, 

Nice, thanks for the alternative-workaround suggestion. 

You didn't ask for it, but you get it anyway: in my opinion, it would make sense if the ixdat reader doesn't (always) try to be smarter than the user. Selecting a specific reader for reading a measurement requires that the user actually knows that this exists, so I would assume that they deliberately choose the EC or MS reader, even if the data contains ECMS data.
This is useful not only for plotting, but also because there are some other features that work for ECMeasurement objects but not for ECMSMeasurement objects (at the moment).
On the other hand, in the current case, where it's just about selecting the plotter, having some option of simply selecting the plotter would be even more practical, because then you don't have to import the same data multiple times if you, say, want to make an ECMS plot vs time, then plot the EC data or MS data of some parts of the data separately (which is something I'm trying to do right now).

**Comment by ScottSoren** [comment] 2022-02-02 15:06
Got it. Only in the case of pure `Measurement.read()` should ixdat readers decide the class of the measurement to return. I agree ixdat is usually not smarter than the user.
Coming in an update ASAP later this week together with the other quick issues.

With regards to selecting the plotter, can you give an example of the code you would like to use to do that?

**Comment by AnnaWiniwarter** [comment] 2022-02-03 10:11
I can imagine a couple of ways how this could be done conveniently. 
`ecms = Measurement.read("path/to/my/tsv/file.tsv", reader="zilien")`
then, to make an ECMS plot, of course `ecms.plot_measurement()`
for plotting MS only eg.
`ecms.plot_measurement_ms(tspan=[1000,2000])` or
`ecms.plot_measurement(tspan=[1000,2000], plotter="ms")`

for plotting EC data, here vs. potential.
`cvs = ecms.cut(tspan = [0,1000])
cvs = cvs.as_cv()
cvs.plot_ec_vs_potential()`
or
`cvs.plot_vs_potential(plotter="ec")`

I would be fine with either option, though selecting the plotter seems like the neater solution to me. in that case, though, I wonder if it would make sense to have an option to plot vs. potential when using plot_measurement (or is this possible already, and I just haven't figured out how to yet?).

**Comment by ScottSoren** [comment] 2022-02-03 17:24
This and the other recent fixes are built into ixdat v0.1.7.
`pip install --upgrade ixdat`  😄
Marking them as solved, please reopen if that proves wrong.

**Comment by AnnaWiniwarter** [comment] 2022-02-04 12:52
I keep forgetting that ECMSMeasurement and ECMSCyclicVoltammogram are entirely different objects. now I get following error
`AttributeError: 'ECMSCyclicVoltammogram' object has no attribute 'ec_plotter'`
Sorry that I didn't specify this before, but I'm opening the issue again now. 

(using ms_plotter works fine)

**Comment by ScottSoren** [comment] 2022-02-04 14:19
oh, right. The problem is I guess the inheritance of `ECMSCyclicVoltammogram` from `MSMeasurement` and `CyclicVoltammogram` rather than from `ECMSMeasurement`. This needs to be fixed. Reopened.

**Comment by ScottSoren** [comment] 2022-02-06 13:35
Fixed. Thanks for bringing this up. It hugely improves the code :D 
70-some lines redefining stuff becomes:
```
class ECMSCyclicVoltammogram(CyclicVoltammogram, ECMSMeasurement):
    """Class for raw EC-MS functionality. Parents: CyclicVoltammogram, ECMSMeasurement"""
```
and like magic `ECMSCyclicVoltammogram` just works.
(I guess I was originally worried there'd be an "incest" problem since `ECMeasurement` now appears twice in its family tree. But  seems to work fine - maybe incest is fine for pythons?)

`cvs.ec_plotter.plot_vs_potential()` etc works now, and redefining cycle and indexing work as before. 

Note that `cvs.plot()` plots vs EC-MS data against potential as always (assignment of `plot` to `plotter.plot_vs_potential` is apparently inherited from `CyclicVoltammogram` as desired), but `cvs.ec_plotter.plot()` doesn't exist since `ECPlotter` is general for normal EC or CV - you have to explicitly call `cvs.ec_plotter.plot_vs_potential()`. 

just distributed `ixdat` again with this update as v0.1.8. 
Closing the issue.

**Closed** 2022-02-06 13:35 UTC

**Comment by KennethNielsen** [comment] 2022-02-21 12:35
I just read through this thread as part of a review. I think I tend to like the idea that a composite technique will have more than one default plotter, one for each of the components and one for the combination **or**, so something along the lines of what you suggested in https://github.com/ixdat/ixdat/issues/32#issuecomment-1029164084. As an alternative, it could also be that each composite measurement, contains components measurements as well, each with their default plotter, so it would become `ecms_measurement.ec_part.plot_measurement()` or something like that. I'm not quite sure of what I prefer, probably the former, although the latter might have some other benefits I can't wrap my head around now.
